import type { Metadata } from "next";
import { Varela } from "next/font/google";
import "./globals.css";

const varela = Varela({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-varela",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${varela.variable} antialiased`}>{children}</body>
    </html>
  );
}
